apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.controllerManager.fullname }}
  labels:
    control-plane: {{ .Values.controlPlane }}
    {{- toYaml .Values.controllerManager.commonLabels | nindent 4 }}
spec:
  {{- if not .Values.controllerManager.autoscaling.enabled }}
  replicas: {{ .Values.controllerManager.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      control-plane: {{ .Values.controlPlane }}
  template:
    metadata:
      labels:
        control-plane: {{ .Values.controlPlane }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.fullname }}
      containers:
        - name: manager
          command:
            - /manager
          args:
            - --leader-elect=true
            - --server-address=:80
            - --cert-dir=/webhook-certs
            - --metrics-bind-address=:8080
            - --health-probe-bind-address=:8081
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: {{ .Values.controllerManager.image.pullPolicy }}
          image: "{{ .Values.controllerManager.image.registry }}/{{ .Values.controllerManager.image.repository }}:{{ .Values.controllerManager.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: restapi-server
              containerPort: {{ .Values.service.restapiServer.port }}
              protocol: TCP
            - name: webhook-server
              containerPort: {{ .Values.service.webhookServer.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.controllerManager.resources | nindent 12 }}