apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.namespace }}
  name: kaishield-eader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kaishield-leader-election-role
subjects:
- kind: ServiceAccount
  namespace: {{ .Values.namespace }}
  name: {{ .Values.serviceAccount.fullname }}